#!/bin/sh

ros2 topic pub -r 4 /diff_drive_controller/cmd_vel geometry_msgs/msg/TwistStamped "{header: {stamp: {sec: 0, nanosec: 0}, frame_id: ''}, twist: {linear: {x: $1, y: 0, z: 0}, angular: {x: 0, y: 0, z: $2}}}"
